#pragma once

#define IISXPRESSHTTPREQUEST_SERVERDISABLED			MAKE_HRESULT(1, FACILITY_ITF, 1)
#define IISXPRESSHTTPREQUEST_NOT200					MAKE_HRESULT(1, FACILITY_ITF, 2)
#define IISXPRESSHTTPREQUEST_INCOMPATIBLECLIENT		MAKE_HRESULT(1, FACILITY_ITF, 3)
#define IISXPRESSHTTPREQUEST_MATCHEDNEVERRULE		MAKE_HRESULT(1, FACILITY_ITF, 4)
#define IISXPRESSHTTPREQUEST_STATICRULEERROR		MAKE_HRESULT(1, FACILITY_ITF, 5)
#define IISXPRESSHTTPREQUEST_USERRULEOVERLOAD		MAKE_HRESULT(1, FACILITY_ITF, 6)
#define IISXPRESSHTTPREQUEST_STATICRULEMATCH		MAKE_HRESULT(1, FACILITY_ITF, 8)
#define IISXPRESSHTTPREQUEST_CPUBUSY				MAKE_HRESULT(1, FACILITY_ITF, 9)
#define IISXPRESSHTTPREQUEST_LEASECONTEXTFAILED		MAKE_HRESULT(1, FACILITY_ITF, 10)
#define IISXPRESSHTTPREQUEST_MEMORYLOW				MAKE_HRESULT(1, FACILITY_ITF, 11)
#define IISXPRESSHTTPREQUEST_ACTIVECONTEXTFAILED	MAKE_HRESULT(1, FACILITY_ITF, 12)
#define IISXPRESSHTTPREQUEST_BADINCOMINGSTREAM		MAKE_HRESULT(1, FACILITY_ITF, 13)