#define IISXPRESS_FILEVERSION			2,6,0,30
#define IISXPRESS_PRODUCTVERSION		2,6,0,30

#define IISXPRESS_FILEVERSION_STRING	"2.6.0.30"
#define IISXPRESS_PRODUCTVERSION_STRING	"2.6.0.30"

#define IISXPRESS_COMPANYNAME_STRING	"Ripcord Software"
#define IISXPRESS_COPYRIGHT_STRING		"Copyright (c) 2005-2010 Ripcord Software. All rights reserved."
