//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IISxpressConsole.rc
//
#define IDS_ERROR_MONITORFAILED         101
#define IDS_INTERNALERROR               102
#define IDS_APP_TITLE                   103
#define IDS_FILTERENABLED               104
#define IDS_FILTERDISABLED              105
#define IDS_ERROR_MISSINGIISXPRESSREGISTRY 106
#define IDS_ERROR_REGISTRYPERMISSIONS   107
#define IDS_ERROR_BADPARAMETER          108
#define IDS_ERROR_UNABLETOSETFILTERENABLESTATUS 109
#define IDS_ERROR_NORUNNINGIISXPRESS    110
#define IDS_ERROR_UNABLETOSETCOMPMODEONSERVER 111
#define IDS_COMPMODE_DEFAULT            112
#define IDS_COMPMODE_SPEED              113
#define IDS_COMPMODE_SIZE               114
#define IDS_COMPMODE_UNKNOWN            115
#define IDS_COMPMODE_STATUSFORMAT       116
#define IDS_ERROR_FAILEDTOSETCOMPMODE   117
#define IDS_SETCOMPMODEOKFORMAT         118
#define IDS_ERROR_COMMANDLINEINCORRECT  119
#define IDS_ERROR_UNABLETOENUMEXTNS     120
#define IDS_ERROR_UNABLETOENUMCTS       121
#define IDS_ERROR_UNABLETOENUMIPS       122
#define IDS_ERROR_UNABLETOENUMURIS      123
#define IDS_ERROR_BADURIFORMAT          124

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
